- name: appsetup
  include_role:
    name: common
    tasks_from: appsetup.yaml
  
- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs.yaml

- name: systemctl setup
  include_role: 
    name: common
    tasks_from: serviceusersetup
