

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /app
    state: directory

- name: download app
  ansible.builtin.get_url:
   url: https://roboshop-artifacts.s3.amazonaws.com/"{{ component }}"-v3.zip 
   dest: /tmp/catalogue.zip

- name: unzipping app
  ansible.builtin.unarchive:
   src: /tmp/catalogue.zip
   dest: /app
   remote_src: yes

- name: copying catalogue.service to systemd
  ansible.builtin.copy:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service
