- name: stopping the running serviceusersetup
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{ component }}"
    state: stopped

- name: removing exist app
  # tags:
  #   - deployment
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating app directory
  ansible.builtin.file:
    state: directory
    path: /app

- name: downloading 
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-{{ app_version }}.zip 
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app

- name: restart application 
  import_role:
    name: common
    tasks_from: serviceusersetup.yaml
