- name: install maven
  ansible.builtin.command: dnf install maven -y

- name: installing 
  ansible.builtin.command: mvn clean package 

- name: maven dependencies download
  ansible.builtin.command: mvn clean package
  args:
    chmod: /app

- name: renamming to shipping.jar
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chmod: /app