- name: install maven
  ansible.builtin.package:
    name: maven
    state: present

- name: maven dependencies download
  ansible.builtin.command: mvn clean package
  args:
    chmod: /app

- name: renamming to shipping.jar
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chmod: /app