- name: Disable mongodb module
  ansible.builtin.command: dnf module disable nodejs -y

- name: Enable nodejs module
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.package:
   name: nodejs
   state: present

- name: Install "catalogue" node.js package.
  community.general.npm:
    path: /app