- name: create user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

- name: copying "{{ component }}".service to systemd
  ansible.builtin.template:
    src: "{{component}}.service.j2"
    dest: /etc/systemd/system/{{component}}.service

- name: system daemon reload
  ansible.builtin.systemd_service:
   daemon_reload: true

- name: cataloge restart and enable
  ansible.builtin.service:
    name: "{{component}}" 
    state: restarted
    enabled: yes