- name: creating system user and dowloading app
  include_role:
    name: common
    tasks_from:  appsetup.yaml

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs

- name: reload and restart system
  include_role:
    name: common
    tasks_from: serviceusersetup


