- name: app_setup
  include_role:
     name: common
     tasks_from: app_setup.yaml

- name: setting up nodejs
  include_role:
    name: common
    tasks_from: nodejs.yaml

- name: copying mongo repot to yum
  ansible.builtin.copy:
    src: mongo.repo
    dest:  /etc/yum.repos.d/mongo.repo

- name: installing mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.ramana.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
  # ignore_errors: true
  # ignore_unreachable: true

- name: print catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
  # ignore_errors: true
  # ignore_unreachable: true

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.ramana.site < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0
  # ignore_errors: true
  # ignore_unreachable: true

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml

- name: deployment
  tags:
  - deployment
  import_role:
    name: commom
    tasks_from: deployment.yaml
  