- name: installmysql server
  ansible.builtin.package:
    name:  mysql-server
    state: present

- name: mysql restart
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: installation of botocore and boto3
  ansible.builtin.pip:
   name: "{{ item }}"
  loop:
  - botocore
  - boto3

- name: changing root password
  vars_files:
  -  vault/mysql.yaml
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ password }}