- name: installmysql server
  ansible.builtin.package:
    name:  mysql-server
    state: present

- name: mysql restart
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install boto3 and botocore
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore

- name: changing root password
  ansible.builtin.commad: mysql_secure_installation --set-root-pass {{ password }}