- name: installmysql server
  ansible.builtin.package:
    name:  mysql-server
    state: present

- name: mysql restart
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: changing root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ password }}