- name: load app content
  include_role:
    name: common
    tasks_from: appsetup.yaml
    

- name: pytho installation
  include_role:
    name: common
    tasks_from: python.yaml

- name: load and create user 
  include_role:
    name: common
    tasks_from: serviceusersetup.yaml
