- name: install redis
  include_role:
   name: common
   tasks_from: redis.yaml


- name: replace default ip address
  ansible.builtin.replace:
    regex: "127.0.0.1"
    replace: "0.0.0.0"

- name: replace protected mode
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: enable and start redis
  ansible.builtin.service:
      name: redis
      state: started
      enabled: yes