- name: appsetup
  include_role:
    name: common
    tasks_from: appsetup.yaml

- name: install maven
  include_role:
    name: common
    tasks_from: maven.yaml

- name: install mysql
  ansible.builtin.package:
    name: mysql
    state: present